plugins {
    id('java')
    id 'net.neoforged.moddev'
}

base.archivesName = "${project.mod_name}-xplat"
version = "${project.minecraft_version}-${project.build_number}"

neoForge {
    neoFormVersion = project.neo_form_version

    validateAccessTransformers = true
    accessTransformers = project.files('src/main/resources/META-INF/accesstransformer_xplat.cfg')
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
}
