plugins {
    id 'java-library'
    id 'idea'
    id 'net.neoforged.moddev'
    id 'eclipse'
}

version = "${project.minecraft_version}-${project.build_number}-NEOFORGE"

neoForge {
    version = project.neoforge_version
    /*
    validateAccessTransformers = true
    accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

     */

    runs {
        configureEach {
            gameDirectory = project.file('../run')
        }
        client {
            client()
        }
        data {
            clientData()
        }
        server {
            server()
            programArgument '--nogui'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(project.sourceSets.main)
        }
    }
}

repositories {
    maven {
        url "https://cursemaven.com"
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${neoforge_version}"
    implementation project(":Xplat")
}

compileJava {
    source(project(":Xplat").sourceSets.main.allSource)
    options.compilerArgs << "-Xlint:all,-classfile,-processing,-deprecation,-serial" << "-Werror"
}

sourcesJar {
    from project(":Xplat").sourceSets.main.allJava
}

processResources {
    from project(":Xplat").sourceSets.main.resources
    inputs.property "version", project.version

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }
}

jar {
     manifest {
        attributes([
            "Specification-Title": "${project.mod_id}",
            "Specification-Vendor": "vazkii",
            "Specification-Version": "1", // We are version 1 of ourselves
            "Implementation-Title": "${project.mod_id}",
            "Implementation-Version": "${project.version}",
            "Implementation-Vendor" :"vazkii",
        ])
    }
}

defaultTasks 'clean', 'build'
